=== giellalt/dict-sme-fin/dtd/smefin.dtd
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( sme ) #IMPLIED
>
<!ATTLIST r
      id ( smefin ) #IMPLIED >


<!-- the header -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'
    xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!ELEMENT e (lg, source?, semantics?, stem*, sources?, mg+) >


<!ELEMENT lg ( l ) >
<!ATTLIST lg freq CDATA #IMPLIED >

<!ELEMENT l (#PCDATA) >
<!ATTLIST l
      ader CDATA #IMPLIED
      pos ( A | Adv | CC | Cmp | CS | Interj | 
      Mal | mwe | N | Num | Pcle | Po | Pr | Pron | V ) #REQUIRED
      nr ( Sg | Du | Pl ) #IMPLIED
      dial ( east | west | torne | varanger ) #IMPLIED
      sem_type ( Obj | Plc | Fem | Org | Mal | Txt ) #IMPLIED 
      type ( Dem | Fem | G3 | G7 | Coll | Indef | Interr | Mal | NomAg | Pers | Prop | Refl | Rel |Ord ) #IMPLIED
>


<!ELEMENT mg (semantics?, l_ref?, tg+ ) >

<!ELEMENT geo (#PCDATA)>
<!ELEMENT gramm (#PCDATA)>
<!ELEMENT tg (semantics?, re?, geo?, gramm?, t+, xg* ) >
<!ATTLIST tg xml:lang ( fin ) #REQUIRED >

<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->

<!ELEMENT t (#PCDATA) >
<!ATTLIST t dial ( east | west | torne | varanger ) #IMPLIED >
<!ATTLIST t t_type ( expl | phrase ) #IMPLIED  >
<!ATTLIST t nr ( Sg | Pl ) #IMPLIED  >
<!ATTLIST t pos ( A | S  | N  | V | Adp | Clt |
            Adv | P | Pr | Po | Det |
            Pron | Prop | I | Interj | CC | CS | Im | Npl | Num |
            Pcle | Prsprc | Phrase | Fp-Cmp | Lp-Cmp | Cmp | X  | Xxx |
      phrase_N | phrase_A | phrase_V | phrase_Adv | g3 | NomAg | mwe | fp-cmp
          | Abbr | Foc_ba
          | Adv-N | N-Pron | Adv-CC | Adv-Pron | Adv-CS | CC-CS | A-N | Adv-Po | CMP | A-Adv | Adv-Po-Pron | A-Adv-Pron | A-Adv-N | Adv-N-Po | N-Po | Po-Pron | A-Pron | Foc_gis | Foc_han ) #IMPLIED >
<!ATTLIST t type ( Prop | Indef | G3 | NomAg | Coll | Recipr | Pers | PrsPrc
                  | Refl | Dem | Poss | Logo | Rel | Interr | TV | IV | Ord ) #IMPLIED >
<!ATTLIST t hid CDATA #IMPLIED >
<!ATTLIST t var ( sw | no | fi )  #IMPLIED >


<!ELEMENT xg ((x, xt+)+)>
<!ATTLIST xg re CDATA #IMPLIED >
<!ELEMENT x (#PCDATA)>
<!ATTLIST x src CDATA #IMPLIED >
<!ELEMENT xt (#PCDATA)>
<!ATTLIST xt src CDATA #IMPLIED >

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-sme-fin/src/pronRel_smefin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/smefin.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smefin" xml:lang="sme">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT, Kotus in Helsinki,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="Pron" type="Rel">gii</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">kuka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Rel">guhte</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">kuka</t>
            <t pos="Pron">joka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Rel">mii</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">mikä</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-fin/src/pronPers_smefin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smefin.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smefin" xml:lang="sme">
  <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT, Kotus in Helsinki,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
  <e>
    <lg>
      <l pos="Pron" type="Pers">dat</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">se</t>
      </tg>
    </mg>
    <mg>
      <tg xml:lang="fin">
        <re>puhek.</re>
        <t pos="Pron">hän</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">dii</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">te</t>
        <xg>
          <x>dii lehpet</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Dis lea beana.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">doai</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">te kaksi</t>
        <xg>
          <x>doai leahppi</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Dudnos lea beana.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">don</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">sinä</t>
        <xg>
          <x>Dus lea gusto stuora beana.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">mii</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">me</t>
        <xg>
          <x>mii leat</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Mis lea beana.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">moai</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">me kaksi</t>
        <xg>
          <x>moai letne</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Munnos lea beana.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">mun</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">minä</t>
        <xg>
          <x>mun lean</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Mus lea beana.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">sii</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">he</t>
        <xg>
          <x>sii leat</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Sis lea beana.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">soai</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">he</t>
        <xg>
          <x>soai leaba</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Sudnos lea beana.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Pers">son</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">hän</t>
        <xg>
          <x>Son liiko stoahkat.</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Sus lea ođđa beaivegirji.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
    </mg>
  </e>
</r>

=== giellalt/dict-sme-fin/src/cs_smefin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/smefin.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smefin" xml:lang="sme">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT, Kotus in Helsinki,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="CS">ahte</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">että</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">amas</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">outo</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">go</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">kun</t>
         </tg>
      </mg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">kuin</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">jos</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">jos</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">juogo</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">joko</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">juos</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">jos</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">nugo</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">niin kuin</t>
            <t pos="CS">kuten</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">ovdalgo</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">ennen kuin</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">vaikko</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">vaikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">jogo ... dahje</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">joko ... tai</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">josgo</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">josko</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">váikko</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">vaikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">dego</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pcle">kuten</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CS">jus</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CS">jos</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-fin/src/cc_smefin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/smefin.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smefin" xml:lang="sme">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT, Kotus in Helsinki,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="CC">ahte</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">että</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">dahe</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">taikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">dahje</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">taikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">daihe</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">taikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">daikke</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">taikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">ja</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">ja</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">muhto</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">mutta</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">vaikke</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">vaikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">vaikko</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">vaikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">sihke</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">sekä</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">dehe</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">tai</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="CC">vai</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="CC">vai</t>
         </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-fin/src/pr_smefin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smefin.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smefin" xml:lang="sme">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT, Kotus in Helsinki,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="Pr">badjel</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pr">yli</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pr">birra</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pr">ympäri</t>
            <t pos="Pr">ympärillä</t>
         <xg>
          <x>Sus lei vierru čuoigat birra ealu.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pr">maŋŋá</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pr">jälkeen</t>
         <xg>
          <x>Guossit buohccájedje dakka maŋŋá doaluid.</x>
          <xt>_FIN_</xt>
        </xg>
        <xg>
          <x>Ánde lei bargagoahtán snihkkárin dalá maŋŋá soađi.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pr">ovdal</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pr">ennen</t>
            <t pos="Pr">aikaisemmin</t>
         <xg>
          <x>Áddjá bođii juo ovdal juovllaid.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pr">guovdelaš</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Adv">keskellä</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pr">earret</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Po">paitsi</t>
         <xg>
          <x>Buohkat bohte earret Niillasa.</x>
          <xt>_FIN_</xt>
        </xg>
      </tg>
      </mg>
   </e>
</r>

=== giellalt/dict-sme-fin/src/pronDem_smefin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../dtd/smefin.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smefin" xml:lang="sme">
   <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT, Kotus in Helsinki,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
   <e>
      <lg>
         <l pos="Pron" type="Dem">dakkár</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">sellainen</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Dem">dakkáraš</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">sellainen</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Dem">diet</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <re>lähellä puhuttavaa</re>
            <t pos="Pron">se</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Dem">dot</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <re>etäällä oleva</re>
            <t pos="Pron">tuo</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Dem">duokkáraš</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">tuollainen</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Dem">duot</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">tuo</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Dem">dákkár</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">tällainen</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="Pron" type="Dem">dát</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="Pron">tämä</t>
         </tg>
      </mg>
   </e>
</r>
