=== giellalt/dict-sme-fin/dtd/smefin.dtd
<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
    xml:lang ( sme ) #IMPLIED
>
<!ATTLIST r
      id ( smefin ) #IMPLIED >


<!-- the header -->
<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'
    xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml"
>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!ELEMENT e (lg, source?, semantics?, stem*, sources?, mg+) >


<!ELEMENT lg ( l ) >
<!ATTLIST lg freq CDATA #IMPLIED >

<!ELEMENT l (#PCDATA) >
<!ATTLIST l
      ader CDATA #IMPLIED
      pos ( A | Adv | CC | Cmp | CS | Interj | 
      Mal | mwe | N | Num | Pcle | Po | Pr | Pron | V ) #REQUIRED
      nr ( Sg | Du | Pl ) #IMPLIED
      dial ( east | west | torne | varanger ) #IMPLIED
      sem_type ( Obj | Plc | Fem | Org | Mal | Txt ) #IMPLIED 
      type ( Dem | Fem | G3 | G7 | Coll | Indef | Interr | Mal | NomAg | Pers | Prop | Refl | Rel |Ord ) #IMPLIED
>


<!ELEMENT mg (semantics?, l_ref?, tg+ ) >

<!ELEMENT geo (#PCDATA)>
<!ELEMENT gramm (#PCDATA)>
<!ELEMENT tg (semantics?, re?, geo?, gramm?, t+, xg* ) >
<!ATTLIST tg xml:lang ( fin ) #REQUIRED >

<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->

<!ELEMENT t (#PCDATA) >
<!ATTLIST t dial ( east | west | torne | varanger ) #IMPLIED >
<!ATTLIST t t_type ( expl | phrase ) #IMPLIED  >
<!ATTLIST t nr ( Sg | Pl ) #IMPLIED  >
<!ATTLIST t pos ( A | S  | N  | V | Adp | Clt |
            Adv | P | Pr | Po | Det |
            Pron | Prop | I | Interj | CC | CS | Im | Npl | Num |
            Pcle | Prsprc | Phrase | Fp-Cmp | Lp-Cmp | Cmp | X  | Xxx |
      phrase_N | phrase_A | phrase_V | phrase_Adv | g3 | NomAg | mwe | fp-cmp
          | Abbr | Foc_ba
          | Adv-N | N-Pron | Adv-CC | Adv-Pron | Adv-CS | CC-CS | A-N | Adv-Po | CMP | A-Adv | Adv-Po-Pron | A-Adv-Pron | A-Adv-N | Adv-N-Po | N-Po | Po-Pron | A-Pron | Foc_gis | Foc_han ) #IMPLIED >
<!ATTLIST t type ( Prop | Indef | G3 | NomAg | Coll | Recipr | Pers | PrsPrc
                  | Refl | Dem | Poss | Logo | Rel | Interr | TV | IV | Ord ) #IMPLIED >
<!ATTLIST t hid CDATA #IMPLIED >
<!ATTLIST t var ( sw | no | fi )  #IMPLIED >


<!ELEMENT xg ((x, xt+)+)>
<!ATTLIST xg re CDATA #IMPLIED >
<!ELEMENT x (#PCDATA)>
<!ATTLIST x src CDATA #IMPLIED >
<!ELEMENT xt (#PCDATA)>
<!ATTLIST xt src CDATA #IMPLIED >

<!ELEMENT xhtml:script EMPTY >
<!ATTLIST xhtml:script type CDATA #FIXED "text/javascript" >
<!ATTLIST xhtml:script src  CDATA #IMPLIED >
<!ATTLIST xhtml:script xmlns:xhtml CDATA #FIXED "http://www.w3.org/1999/xhtml" >

=== giellalt/dict-sme-fin/src/pronInterr_smefin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual" "../dtd/smefin.dtd">
<r xmlns:xhtml="http://www.w3.org/1999/xhtml" id="smefin" xml:lang="sme">
  <lics xmlns:xhtml="http://www.w3.org/1999/xhtml" xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Giellatekno at UiT, Kotus in Helsinki,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
   </lics>
  <e>
    <lg>
      <l pos="Pron" type="Interr">gii</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">kuka</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Interr">goabbá</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">kumpi</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Interr">makkár</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">millainen</t>
        <t pos="Pron">minkälainen</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Interr">makkáraš</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">millainen</t>
        <t pos="Pron">minkälainen</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron" type="Interr">mii</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">mikä</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">dokkár</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="A">tuollainen kuin tuo tuolla kaukana</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">giige</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">kukaan</t>
      </tg>
    </mg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">kukin</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">guhtet</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">kukin</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">juobbá</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">jompikumpi</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">juobbágoabbá</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">jompikumpi</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">juohkehaš</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">jokainen</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">miijai</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">mikin</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">oktahat</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Num">yksi ja sama</t>
      </tg>
    </mg>
  </e>
  <e>
    <lg>
      <l pos="Pron">olugat</l>
    </lg>
    <mg>
      <tg xml:lang="fin">
        <t pos="Pron">monet ihmiset</t>
      </tg>
    </mg>
  </e>
</r>
